services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - ./.env
    # Check if the database is awake (using the updated mariadb-admin command!)
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - inception
    restart: always 
    volumes:
      - mariadb_vol:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: ./.env
    # Wait for the MariaDB healthcheck to pass before booting WordPress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: always
    volumes:
      - wordpress_vol:/var/www/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wordpress_vol:/var/www/wordpress

# Declare the custom bridge network so containers can talk to each other
networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress


# Secrets storing the passwords
secrets:
  db_password:
    file: ../secrets/mariadb/db_password

  db_root_password:
    file: ../secrets/mariadb/db_root_password

  wp_admin_password:
    file: ../secrets/wordpress/wp_admin_password
  
  wp_user_password:
    file: ../secrets/wordpress/wp_user_password